const emojiDictionary = {
  "😅": "Grinning Face with Sweat",
  "🤣": "Rolling on the Floor Laughing",
  "😂": "Face with Tears of Joy",
  "🙂": "Slightly Smiling Face",
  "🙃": "Upside-Down Face",
  "😉": "Winking Face",
  "😊": "Smiling Face with Smiling Eyes",
  "😝": "Squinting Face with Tongue",
  "☘️": "Shamrock",
  "🍀": "Four Leaf Clover",
  "🍁": "Maple Leaf",
  "🍂": "Fallen Leaf",
  "🍃": "Leaf Fluttering In Wind",
  "🌼": "Blossom",
  "🌻": "Sunflower",
  "🌷": "Tulip",
  "🌱": "Seedling",
  "🌲": "Evergreen Tree",
  "🌳": "Deciduous Tree",
  "🌴": "Palm Tree",
  "🌵": "Cactus",
  "🌾": "Sheaf Of Rice",
  "🌿": "Herb",
  "🦂": "Scorpion",
  "🦟": "Mosquito",
  "🦠": "Microbe",
  "💐": "Bouquet",
  "🌸": "Cherry Blossom",
  "💮": "White Flower",
  "🏵️": "Rosette",
  "🌹": "Rose",

  "🐇": "Rabbit",
  "🐿️": "Chipmunk",
  "🦔": "Hedgehog",
  "🦇": "Bat",
  "🐻": "Bear",
  "🐨": "Koala",
  "🐏": "Ram",
  "🐐": "Goat",
  "🐪": "Camel",
  "🦒": "Giraffe",
  "🐘": "Elephant",
  "🦏": "Rhinoceros",
  "🦛": "Hippopotamus",
  "🐄": "Cow",
  "🐷": "Pig Face",
  "🦓": "Zebra",
  "🦌": "Deer",
  "🐂": "Ox",
  "🦝": "Raccoon",
  "🐈": "Cat",
  "🦁": "Lion",
  "🐅": "Tiger",
  "🐆": "Leopard",
  "🦄": "Unicorn",
  "🦍": "Gorilla",
  "🐕": "Dog",
  "🐺": "Wolf",
  "🦊": "Fox",
};

export default emojiDictionary;
